/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.review;

import com.review.App;

public class AppTest {
  //@Test public void appHasAGreeting() {
  App classUnderTest = new App();
}
